services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
    - db
    - redis
    networks:
    - backend_network
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - backend_network

  redis:
    image: redis:7
    container_name: redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network

volumes:
  postgres_data:
  redis_data:

networks:
  backend_network: